spring:
  application:
    name: breeze
  profiles:
    active: dev
  messages:
    encoding: utf-8
    basename: static/i18n/messages
  mail:
    username: xxxx@xxx.com
    password: xxxxxxx
    host: smtp.xxx.cn
    port: 25
    default-encoding: UTF-8
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /breeze
# 线程池配置
thread:
  task:
    pool:
      corePoolSize: 20
      maxPoolSize: 40
      keepAliveSeconds: 300
      queueCapacity: 50
# 系统设置相关配置
app:
  name: Breeze
  host: localhost:4200
# 用户登录token配置参数
token:
  tokenValidityInSeconds: 3600000
  longTokenValidityInSeconds: 604800000
