# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: 
    - master
    - develop
  pull_request:
    branches: 
    - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo begin build project
      - name: Setup Java JDK 
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B -Dmaven.test.skip=true clean package --file pom.xml
      
      
